[server]
headless = true
enableCORS = false

[logger]
level = "error"  # suppresses most Streamlit logs (set to "warning" for more visibility)

[theme]
base="dark"                # or "light"
primaryColor="#1DB954"     # Spotify green
backgroundColor="#121212"  # Spotify dark background
secondaryBackgroundColor="#191414"
textColor="#FFFFFF"
font="sans serif"

[global]
developmentMode = false